### ISSUE TITLE
Open Arc is being considered closed

### ISSUE THREAD

**Issue by kashif-izhar** [calda/CGPathIntersection#5]
In the attached project sample, if you draw a line on the diagonals it selects the diagonal line as well as both arcs because it is considering the CHORD of the arc as part of the path which it is not since the arc is open.

This issue seems to be resolved if you comment out line # 45 `context.closePath()` in file **CGPathImage.swift**

However, I am not sure of the repercussions of doing so.

[CoolDraw.zip](https://github.com/calda/CGPathIntersection/files/7095390/CoolDraw.zip)

**Comment by calda** [comment]
The test suite still passes if I remove `context.beginPath()` and `context.closePath()` from `CGPathImage.init`, so it must be unnecessary. Fixed in https://github.com/calda/CGPathIntersection/commit/5b6ad9647e8ec3a557c5879cb848c5ac7f37cae9.
